FROM python:3.11

WORKDIR /code

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements file
COPY ./app/requirements.txt /code/app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r /code/app/requirements.txt

# Copy the rest of the application code
COPY ./app/Model/classification  /code/app/Model/classification
COPY ./app/Model/objectDetectionNoFolds  /code/app/Model/objectDetectionNoFolds
COPY ./app/main.py /code/app/main.py

# Expose the port and run the application
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

